version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: hub-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hub_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hub-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: hub-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  auth-service:
    build: ./auth-service
    container_name: hub-auth
    depends_on:
      - postgres
      - keycloak
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hub_auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: hub-projetos-sociais
      KEYCLOAK_CLIENT_ID: auth-service
      KEYCLOAK_CLIENT_SECRET: jgMCBkT0cYEEA4oVgInqDv2S86f2dAZa

    ports:
      - "8081:8080"

volumes:
  postgres_data: